# Generated by Django 2.2 on 2019-04-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('sede', models.CharField(max_length=100, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(max_length=30, verbose_name='Segundo Apellido')),
                ('fecha_nac', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='partido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('localizacion', models.CharField(max_length=30)),
                ('fase', models.CharField(choices=[('Primera Fase', 'Primera Fase'), ('Segunda Fase', 'Segunda Fase'), ('Fase Final', 'Fase Final'), ('Fase Ascenso', 'Fase de Ascenso')], max_length=100)),
                ('cuarto1', models.CharField(max_length=5)),
                ('cuarto2', models.CharField(max_length=5)),
                ('cuarto3', models.CharField(max_length=5)),
                ('cuarto4', models.CharField(max_length=5)),
                ('tiempos_extra', models.CharField(max_length=5)),
                ('tanteo_final', models.CharField(max_length=7)),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Local', to='BasketMVC.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Visitante', to='BasketMVC.equipo')),
                ('jugadores', models.ManyToManyField(related_name='Jugadores', to='BasketMVC.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='stats_jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jugador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BasketMVC.jugador')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BasketMVC.partido')),
            ],
            options={
                'unique_together': {('id_jugador', 'id_partido')},
            },
        ),
        migrations.CreateModel(
            name='stats_equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BasketMVC.equipo')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BasketMVC.partido')),
            ],
            options={
                'unique_together': {('id_equipo', 'id_partido')},
            },
        ),
    ]
