# Generated by Django 2.2 on 2019-05-30 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasketMVC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='dorsal',
            field=models.CharField(default='0', max_length=3, verbose_name='Dorsal'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Equipo', to='BasketMVC.equipo'),
        ),
    ]
