# Generated by Django 2.2.1 on 2019-06-05 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasketMVC', '0007_auto_20190605_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='TIEMPO',
            field=models.TimeField(default=datetime.datetime(2019, 6, 5, 20, 35, 8, 553289), verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='stats_equipo',
            name='TIEMPO',
            field=models.TimeField(default=datetime.datetime(2019, 6, 5, 20, 35, 8, 557290), verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='stats_jugador',
            name='TIEMPO',
            field=models.TimeField(default=datetime.datetime(2019, 6, 5, 20, 35, 8, 555289), verbose_name='Tiempo'),
        ),
    ]
