# Generated by Django 2.2 on 2019-06-06 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasketMVC', '0008_auto_20190605_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='TIEMPO',
            field=models.TimeField(default=datetime.datetime(2019, 6, 6, 8, 22, 49, 642453), verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='stats_equipo',
            name='TIEMPO',
            field=models.TimeField(default=datetime.datetime(2019, 6, 6, 8, 22, 49, 642453), verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='stats_jugador',
            name='TIEMPO',
            field=models.TimeField(default=datetime.datetime(2019, 6, 6, 8, 22, 49, 642453), verbose_name='Tiempo'),
        ),
    ]
