# Generated by Django 2.2.1 on 2019-06-06 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasketMVC', '0010_auto_20190606_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='jugadores',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='TIEMPO',
            field=models.TimeField(default=datetime.datetime(2019, 6, 6, 19, 33, 46, 351072), verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='stats_equipo',
            name='TIEMPO',
            field=models.TimeField(default=datetime.datetime(2019, 6, 6, 19, 33, 46, 356041), verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='stats_jugador',
            name='TIEMPO',
            field=models.TimeField(default=datetime.datetime(2019, 6, 6, 19, 33, 46, 354070), verbose_name='Tiempo'),
        ),
    ]
