# Generated by Django 2.2.1 on 2019-06-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasketMVC', '0013_auto_20190606_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats_equipo',
            name='TIEMPO',
        ),
    ]
