# Generated by Django 2.2.1 on 2019-06-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasketMVC', '0015_remove_jugador_tiempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='puntos_contra',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='puntos_favor',
        ),
    ]
